# Part 3 (2.4): search, difficulty filter, results cards, quiz by touch, login/register/forgot UX, guest import, contrast (axe-core)
# usage: python3 tests/e2e/part3.py <out-dir>   (server from tests/e2e/run.sh: class code P4P4P4, s1/s2 Stud1234, kru4/Teach1234)
import asyncio, sys, json, os, subprocess, re
from playwright.async_api import async_playwright
OUT=sys.argv[1]; BASE='http://127.0.0.1:3990'
ROOT=os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
R2=json.loads(subprocess.check_output(['node','-e',"const {ALL}=require('./content/labs');const r=ALL.find(l=>l.id==='r2');console.log(JSON.stringify(r.tasks.map(t=>t.options[t.correct])))"],cwd=ROOT))
AXE_PATH=os.path.join(ROOT,'node_modules','axe-core','axe.min.js')
issues=[]
def bad(m): issues.append(m); print('  ✗',m)
def ok(m): print('  ✓',m)
def check(c,m): ok(m) if c else bad(m)
async def login(ctx,u,p):
    r=await ctx.request.post(BASE+'/api/auth/login',data={'username':u,'password':p},headers={'X-NetLab':'1'}); assert r.ok, await r.text()

async def main():
    async with async_playwright() as p:
        b=await p.chromium.launch()
        ctx=await b.new_context(viewport={'width':390,'height':844},has_touch=True,is_mobile=True); await login(ctx,'s1','Stud1234')
        pg=await ctx.new_page(); E=[]; pg.on('pageerror',lambda e:E.append(str(e)))
        print('== search')
        await pg.goto(BASE+'/#/learn'); await pg.wait_for_selector('.unitlist')
        await pg.tap('#hamb'); await pg.fill('#side .sidesearch input','ซับเน็ต'); await pg.keyboard.press('Enter'); await pg.wait_for_timeout(700)
        n=await pg.locator('#app .reslist a').count(); check(n>0,f'Thai "ซับเน็ต" + Enter finds {n} lessons (synonyms)')
        await pg.goto(BASE+'/#/search/'+'Firewall'); await pg.wait_for_timeout(500); check(await pg.locator('#app .reslist a').count()>0,'English "Firewall" finds lessons')
        await pg.goto(BASE+'/#/search/'+'qqqxyz'); await pg.wait_for_timeout(500); check('ไม่พบ' in await pg.inner_text('#app'),'no match shows an empty state with advice')
        print('== practice difficulty filter')
        await pg.evaluate('localStorage.removeItem("netlab-practice")'); await pg.goto(BASE+'/#/learn'); await pg.goto(BASE+'/#/practice'); await pg.wait_for_selector('.fchip')
        st=await pg.inner_text('.lvstate'); check('ทุกระดับ' in st,'default: all levels selected and stated ('+st+')')
        await pg.locator('.fchip.lv-easy').tap(); st=await pg.inner_text('.lvstate')
        check(st.endswith('ง่าย') and await pg.locator('.fchip.lv-easy[aria-pressed=true]').count()==1,'tap "ง่าย": only easy selected')
        await pg.locator('.fchip.lv-hard').tap(); st=await pg.inner_text('.lvstate'); check('ง่าย' in st and 'ยาก' in st,'tap "ยาก": easy + hard')
        async with pg.expect_response(lambda r:'/api/practice/questions' in r.url) as rr:
            await pg.tap('button:has-text("เริ่มฝึก")')
        qs=(await (await rr.value).json())['questions']; check(qs and all(q['level'] in ('easy','hard') for q in qs),f'drawn questions respect the filter ({len(qs)})')
        await pg.wait_for_selector('.bq')
        await pg.locator('.bq label.opt, .bq .fillq input, .bq select, .bq .cmdin, .bq .subgrid input, .bq .obtn').first.tap(); ok('answer control tappable')
        await pg.goto(BASE+'/#/learn'); await pg.goto(BASE+'/#/practice'); await pg.wait_for_selector('.fchip')
        await pg.locator('.fchip:has-text("ทุกระดับ")').tap(); check('ทุกระดับ' in await pg.inner_text('.lvstate'),'"ทุกระดับ" selects all again')
        print('== quiz by touch (pre-test)')
        await pg.goto(BASE+'/#/lesson/w6/pre'); await pg.wait_for_selector('.opt')
        await pg.locator('.qcard').nth(0).locator('label.opt').nth(2).tap()
        check(await pg.locator('.qcard').nth(0).locator('input:checked').count()==1,'tapping an option selects it')
        print('== results: cards on phone, table on tablet')
        await pg.goto(BASE+'/#/results'); await pg.wait_for_selector('.rescard')
        titles=await pg.locator('.rescard .rchead a').all_inner_texts()
        check(len(titles)==18 and len(set(titles))==18 and all(re.match(r'^สัปดาห์ \d+: \S',t) for t in titles),'18 week cards, titles complete and unique')
        check(not await pg.locator('.restable').is_visible(),'phone shows cards, not the squeezed table')
        check(await pg.evaluate('document.documentElement.scrollWidth-innerWidth')<=0,'results fit 390px')
        await pg.screenshot(path=f'{OUT}/p3_390_results.png',full_page=False)
        t=await b.new_context(viewport={'width':768,'height':1024},has_touch=True); await login(t,'s1','Stud1234'); tp=await t.new_page()
        await tp.goto(BASE+'/#/results'); await tp.wait_for_selector('.restable')
        check(await tp.locator('.restable tbody tr').count()==18 and not await tp.locator('.rescards').is_visible(),'tablet shows the table (18 rows)')
        await tp.locator('.restable').evaluate('e=>e.scrollTop=400'); await tp.wait_for_timeout(200)
        hb=await tp.locator('.restable thead th').first.bounding_box(); wb=await tp.locator('.restable').bounding_box()
        check(abs(hb['y']-wb['y'])<3,'table header stays visible while scrolling inside the frame')
        await tp.screenshot(path=f'{OUT}/p3_768_results.png'); await t.close()
        check(not E,'no JS errors: '+'; '.join(E[:2])); await ctx.close()

        print('== guest work, register with class code, link progress')
        g=await b.new_context(viewport={'width':390,'height':844},has_touch=True,is_mobile=True); gp=await g.new_page(); E=[]; gp.on('pageerror',lambda e:E.append(str(e))); gp.on('dialog',lambda d: asyncio.ensure_future(d.accept()))
        await gp.goto(BASE+'/#/'); await gp.wait_for_selector('.guestbar')
        check('เก็บเฉพาะในเบราว์เซอร์นี้' in await gp.inner_text('.guestbar'),'guest warning banner explains where scores are kept')
        await gp.fill('#nm','มานะ ทดสอบ ปวช.2/4 เลขที่ 7')
        await gp.goto(BASE+'/#/room/r2'); await gp.locator('.btn.start').tap(); await gp.wait_for_selector('#task-r2-0 .choice')
        for i in range(2):
            await gp.locator(f'#task-r2-{i} .choice',has_text=R2[i]).first.tap(); await gp.wait_for_selector(f'#task-r2-{i}.solved')
        ok('guest solved 2 tasks in room r2')
        await gp.goto(BASE+'/#/lesson/w1/content'); await gp.wait_for_timeout(1500)
        await gp.evaluate('window.scrollTo(0,document.body.scrollHeight)'); await gp.wait_for_timeout(1500)
        await gp.goto(BASE+'/#/'); await gp.wait_for_selector('.guestbar')
        await gp.locator('.guestbar button:has-text("สมัครด้วยรหัสห้อง")').tap(); await gp.wait_for_selector('.modal-back form')
        check('ผูกเข้าบัญชีใหม่ได้' in await gp.inner_text('.modal-back'),'register form mentions linking guest work')
        inp=gp.locator('.modal-back input')
        await inp.nth(0).fill('p4p4p4'); check(await inp.nth(0).input_value()=='P4P4P4' and 'รหัสห้องมี 6 ตัว' not in await gp.inner_text('.modal-back'),'class code is upper-cased while typing and accepted')
        await inp.nth(3).fill('Bad Name!'); check('ใช้ได้เฉพาะ' in await gp.inner_text('.modal-back'),'invalid username explained inline')
        await inp.nth(1).fill('7'); await inp.nth(2).fill('มานะ ทดสอบ'); await inp.nth(3).fill('mana.test')
        await inp.nth(4).fill('short'); check('ยังสั้นไป' in await gp.inner_text('.modal-back'),'weak password explained inline')
        await inp.nth(4).fill('mana12345'); await inp.nth(5).fill('mana12345')
        await gp.locator('.modal-back .pweye').first.tap(); check(await inp.nth(4).get_attribute('type')=='text','"แสดง" reveals the password')
        await gp.screenshot(path=f'{OUT}/p3_390_register.png')
        await gp.locator('.modal-back button[type=submit]').tap()
        await gp.wait_for_selector('.modal-back:has-text("ผูกความคืบหน้าเข้าบัญชี")',timeout=10000)
        txt=await gp.inner_text('.modal-back'); check('ตอบโจทย์แล็บถูก 2 ข้อ' in txt,'import offer lists the guest work')
        await gp.screenshot(path=f'{OUT}/p3_390_import.png')
        await gp.locator('.modal-back button:has-text("ผูกเข้าบัญชีนี้")').tap(); await gp.wait_for_selector('.modal-back .msg.ok')
        res=await gp.inner_text('.modal-back .msg.ok'); check('แล็บ 1 ชุด (2 ข้อ)' in res,'imported: '+res)
        await gp.locator('.modal-back button:has-text("เสร็จสิ้น")').tap(); await gp.wait_for_timeout(800)
        await gp.goto(BASE+'/#/room/r2'); await gp.wait_for_selector('#task-r2-0')
        check(await gp.locator('#task-r2-0.solved').count()==1 and await gp.locator('#task-r2-1.solved').count()==1,'account now shows the imported answers')
        await gp.goto(BASE+'/#/'); await gp.wait_for_timeout(800); check(await gp.locator('.modal-back').count()==0,'offer not shown again')
        check(not E,'no JS errors: '+'; '.join(E[:2])); await g.close()

        print('== login modal, forgot password, teacher resolves')
        g=await b.new_context(viewport={'width':360,'height':640},has_touch=True,is_mobile=True); gp=await g.new_page()
        await gp.goto(BASE+'/#/'); await gp.wait_for_selector('.mtop .sbtn'); await gp.locator('.mtop .sbtn').tap(); await gp.wait_for_selector('.modal-back form')
        await gp.keyboard.press('Tab'); await gp.keyboard.press('Tab'); await gp.keyboard.press('Tab'); await gp.keyboard.press('Tab'); await gp.keyboard.press('Tab'); await gp.keyboard.press('Tab'); await gp.keyboard.press('Tab')
        check(await gp.evaluate('!!document.activeElement.closest(".modal-back")'),'keyboard focus stays inside the login modal')
        await gp.keyboard.press('Escape'); await gp.wait_for_timeout(200); check(await gp.locator('.modal-back').count()==0,'Escape closes the modal')
        await gp.locator('.mtop .sbtn').tap(); await gp.wait_for_selector('.modal-back form')
        await gp.fill('.modal-back input >> nth=0','s2'); await gp.locator('.modal-back button:has-text("ลืมรหัสผ่าน")').tap()
        await gp.wait_for_selector('.modal-back:has-text("ส่งคำขอถึงครู")'); check(await gp.locator('.modal-back input').first.input_value()=='s2','forgot form keeps the typed username')
        await gp.locator('.modal-back button[type=submit]').tap(); await gp.wait_for_selector('.modal-back .msg.ok'); m1=await gp.inner_text('.modal-back .msg.ok')
        await gp.screenshot(path=f'{OUT}/p3_360_forgot.png')
        r=await g.request.post(BASE+'/api/auth/forgot',data={'username':'nobody.here'},headers={'X-NetLab':'1'}); m2=(await r.json())['message']
        check(m1==m2,'same reply for an unknown username (no account discovery)')
        t=await b.new_context(viewport={'width':1280,'height':900}); await login(t,'kru4','Teach1234'); tp=await t.new_page(); tp.on('dialog',lambda d: asyncio.ensure_future(d.accept()))
        await tp.goto(BASE+'/teacher.html'); await tp.wait_for_selector('.side')
        check('ขอรหัส 1' in await tp.inner_text('.side'),'teacher sidebar shows the request')
        await tp.locator('.side .navbtn').nth(1).click(); await tp.wait_for_selector('.tabs'); await tp.locator('.tabs button',has_text='นักเรียน').click(); await tp.wait_for_selector('.reqcard')
        await tp.locator('.reqcard button:has-text("ตั้งรหัสชั่วคราว")').click(); await tp.wait_for_selector('table.creds')
        temp=(await tp.locator('table.creds tr').nth(1).locator('td').nth(3).inner_text()).strip()
        check(len(temp)>=6 and await tp.locator('.reqcard').count()==0,'teacher set a temporary password; request cleared')
        await tp.locator('.tabs button',has_text='คะแนนแล็บ').click(); await tp.wait_for_selector('.matrix'); await tp.locator('label:has-text("แสดงเฉพาะงานที่มอบหมาย") input').uncheck() if await tp.locator('label:has-text("แสดงเฉพาะงานที่มอบหมาย") input').is_checked() else None
        await tp.wait_for_timeout(300); check(await tp.locator('.matrix td.cell.imported').count()>=1,'teacher score matrix marks the imported lab with *')
        await tp.screenshot(path=f'{OUT}/p3_teacher_imported.png'); await t.close()
        await gp.locator('.modal-back button:has-text("กลับไปหน้าเข้าสู่ระบบ")').tap(); await gp.wait_for_selector('.modal-back[aria-label="เข้าสู่ระบบ"]')
        await gp.fill('.modal-back input >> nth=0','s2'); await gp.fill('.modal-back input >> nth=1',temp); await gp.locator('.modal-back button[type=submit]').tap()
        await gp.wait_for_selector('.modal-back:has-text("ตั้งรหัสผ่านใหม่")'); ok('student logs in with the temporary password and must set a new one')
        await g.close()

        print('== colour contrast and names (axe-core), light + dark')
        if os.path.exists(AXE_PATH):
            AXE=open(AXE_PATH).read(); viol=[]
            for theme in ['light','dark']:
                c=await b.new_context(viewport={'width':1280,'height':900},color_scheme=theme); await login(c,'s1','Stud1234'); cp=await c.new_page()
                for rt in ['#/','#/learn','#/results','#/lesson/w3/pre','#/lesson/w3/content','#/sims','#/sim/topology','#/sim/subnet','#/sim/crimp','#/sim/terminal','#/sim/troubleshoot','#/practice','#/me']:
                    await cp.goto(BASE+'/'+rt); await cp.wait_for_timeout(1100); await cp.add_script_tag(content=AXE)
                    v=await cp.evaluate("async()=>{const r=await axe.run(document,{runOnly:{type:'rule',values:['color-contrast','button-name','link-name','label','select-name']}});return r.violations.map(v=>v.id+':'+v.nodes.length)}")
                    if v: viol.append(f'{theme} {rt} {v}')
                await c.close()
            check(not viol,'axe-core: no contrast or naming problems in light and dark '+'; '.join(viol[:4]))
        else: print('  (axe-core not installed: npm i -D axe-core to run this check)')
        await b.close()
    print('\nISSUES',len(issues)); [print(' -',i) for i in issues]
asyncio.run(main())

sys.exit(1 if issues else 0)
