'use strict';
// Parallel post-test (form B) for w11, index-aligned with quiz (form A) in ../w11.js
module.exports = [
  { type: 'choice', level: 'easy',
    q: 'เคอร์เนล Linux ถูกเผยแพร่ครั้งแรกโดยใคร และในปีใด',
    options: ['Ken Thompson ปี 1969', 'Linus Torvalds ปี 1991', 'บริษัท Novell ปี 1983', 'Sun Microsystems ปี 2010'], correct: 1,
    explain: 'Linus Torvalds นักศึกษาชาวฟินแลนด์เผยแพร่เคอร์เนล Linux ในปี 1991 เป็นซอฟต์แวร์โอเพนซอร์สที่ชุมชนพัฒนาต่อจนถึงปัจจุบัน',
    why: ['Ken Thompson ร่วมสร้าง UNIX ที่ Bell Labs ราวปี 1969', '', 'Novell ออก NetWare รุ่นแรกในปี 1983', 'ปี 2010 คือปีที่ Oracle ซื้อกิจการ Sun'] },
  { type: 'choice', level: 'easy',
    q: 'ครูติดตั้ง VMware Workstation บนเครื่องที่ใช้ Ubuntu Desktop แล้วสร้างเครื่องจำลองที่ติดตั้ง Windows Server 2022 ข้อใดคือ Guest',
    options: ['Ubuntu Desktop', 'VMware Workstation', 'Windows Server 2022', 'ฮาร์ดแวร์ของเครื่องจริง'], correct: 2,
    explain: 'Guest คือระบบปฏิบัติการที่ทำงานอยู่ภายในเครื่องจำลอง ในที่นี้คือ Windows Server 2022 ส่วน Ubuntu Desktop บนเครื่องจริงคือ Host',
    why: ['Ubuntu Desktop ติดตั้งบนเครื่องจริงและรันโปรแกรมจำลอง จึงเป็น Host', 'VMware Workstation คือ Hypervisor', '', 'ฮาร์ดแวร์จริงเป็นของ Host ที่แบ่งให้ Guest'] },
  { type: 'choice', level: 'medium',
    q: 'ข้อใดเป็น Hypervisor แบบ Type 2 (Hosted) ทั้งหมด',
    options: ['VMware ESXi, Hyper-V, Xen', 'VirtualBox, VMware ESXi, Proxmox VE', 'Hyper-V, VMware Fusion, Xen', 'VirtualBox, VMware Workstation, Parallels Desktop'], correct: 3,
    explain: 'Type 2 ติดตั้งเป็นโปรแกรมบน Host OS เช่น VirtualBox, VMware Workstation และ Parallels Desktop ส่วน ESXi, Hyper-V, Xen และ Proxmox VE เป็น Type 1 ที่ทำงานบนฮาร์ดแวร์โดยตรง',
    why: ['ทั้งสามตัวเป็น Type 1 (Bare-metal)', 'ESXi และ Proxmox VE เป็น Type 1', 'Hyper-V และ Xen เป็น Type 1 มีเพียง Fusion ที่เป็น Type 2', ''] },
  { type: 'choice', level: 'medium',
    q: 'โน้ตบุ๊กที่ใช้ CPU ของ AMD เปิดเครื่องจำลองแล้วขึ้นข้อความว่า AMD-V is disabled in the BIOS ควรแก้ไขอย่างไร',
    options: ['เข้า BIOS/UEFI แล้วเปิด SVM Mode', 'ย้ายไฟล์เครื่องจำลองไปไว้ใน SSD', 'ลดจำนวน CPU เสมือนเหลือ 1 ตัว', 'เปลี่ยนโหมดเครือข่ายเป็น Host-only'], correct: 0,
    explain: 'AMD-V เป็นความสามารถช่วยจำลองเครื่องของ CPU AMD ที่ต้องเปิดใน BIOS/UEFI ก่อน โดย BIOS หลายรุ่นใช้ชื่อเมนูว่า SVM Mode',
    why: ['', 'ความเร็วดิสก์ไม่เกี่ยวกับการเปิด AMD-V', 'จำนวน CPU เสมือนไม่ได้ทำให้ AMD-V ถูกเปิด', 'โหมดเครือข่ายไม่เกี่ยวกับความสามารถของ CPU'] },
  { type: 'choice', level: 'medium',
    q: 'สำนักงานมีพนักงาน 120 คน ใช้ Windows ทุกเครื่อง ต้องการให้ทุกคนใช้บัญชีเดียวเข้าได้ทุกเครื่องและกำหนดนโยบายจากศูนย์กลาง โดยทีมไอทีถนัด Windows ควรเลือก NOS ใด',
    options: ['Novell NetWare 6.5', 'Windows Server', 'Windows 11 Pro', 'Solaris บนเครื่อง SPARC'], correct: 1,
    explain: 'Windows Server มี Active Directory สำหรับจัดการบัญชีและนโยบายจากศูนย์กลาง และทำงานร่วมกับเครื่องลูกข่าย Windows ได้ดี',
    why: ['NetWare เลิกพัฒนาแล้ว ไม่เหมาะกับระบบใหม่', '', 'Windows 11 Pro เป็น OS ส่วนบุคคล ไม่มีบริการ Active Directory', 'Solaris เน้นงาน UNIX ขององค์กรใหญ่ ไม่ได้เด่นเรื่องจัดการเครื่อง Windows'] },
  { type: 'choice', level: 'hard',
    q: 'นักเรียนต้องการฝึก Ubuntu Server บนโน้ตบุ๊กส่วนตัว แต่ยังต้องใช้ Windows ทำการบ้านทุกวัน ควรเลือกแนวทางใด',
    options: ['ลบ Windows แล้วติดตั้ง VMware ESXi ลงโน้ตบุ๊ก', 'ซื้อเซิร์ฟเวอร์จริงอีกเครื่องเพื่อติดตั้งแยก', 'ติดตั้ง VirtualBox ซึ่งเป็น Type 2 บน Windows', 'ติดตั้ง Ubuntu Server ทับ Windows ทั้งเครื่อง'], correct: 2,
    explain: 'Hypervisor Type 2 ติดตั้งเป็นโปรแกรมบน Host OS จึงใช้ Windows ได้ตามปกติ และเปิดเครื่องจำลอง Ubuntu Server ฝึกได้เมื่อต้องการ เหมาะกับการเรียนและทดสอบ',
    why: ['ESXi เป็น Type 1 ติดตั้งแทน OS ทำให้ใช้ Windows ทำการบ้านไม่ได้', 'สิ้นเปลืองเกินจำเป็น เครื่องจำลองทำได้บนเครื่องเดียว', '', 'Windows จะหายไป ทำการบ้านไม่ได้'] },
  { type: 'multi', level: 'easy',
    q: 'ข้อใดเป็นระบบในสายพันธุ์ UNIX ที่บริษัทต่าง ๆ นำไปพัฒนาต่อ (เลือกได้หลายข้อ)',
    options: ['AIX ของ IBM', 'Windows Server 2022', 'HP-UX ของ HP', 'Novell NetWare 6.5'], correct: [0, 2],
    explain: 'AIX (IBM) และ HP-UX (HP) เป็น UNIX เชิงพาณิชย์ เช่นเดียวกับ Solaris ส่วน Windows Server มาจากสาย Windows NT และ NetWare เป็นระบบของ Novell ที่ไม่ใช่ UNIX' },
  { type: 'multi', level: 'hard',
    q: 'องค์กรย้ายเซิร์ฟเวอร์ 10 เครื่องไปเป็นเครื่องจำลองบนเซิร์ฟเวอร์จริง 2 เครื่อง ข้อใดถูกต้อง (เลือกได้หลายข้อ)',
    options: ['ช่วยลดค่าไฟ พื้นที่ และค่าฮาร์ดแวร์', 'ทรัพยากรของเครื่องจำลองยังแบ่งมาจากเครื่องจริง', 'เครื่องจำลองแต่ละตัวมี RAM ไม่จำกัด', 'ไม่จำเป็นต้องสำรองข้อมูลอีกต่อไป'], correct: [0, 1],
    explain: 'การรวมเซิร์ฟเวอร์ด้วย Virtualization ลดค่าไฟ พื้นที่ และฮาร์ดแวร์ แต่ CPU, RAM และดิสก์ของเครื่องจำลองทุกตัวยังแบ่งมาจากเครื่องจริง และยังต้องสำรองข้อมูลเสมอ' },
  { type: 'tf', level: 'easy',
    q: 'Oracle VirtualBox ปัจจุบันเป็นผลิตภัณฑ์ของบริษัท Microsoft ถูกหรือผิด',
    answer: false,
    explain: 'ผิด VirtualBox เดิมพัฒนาโดย Innotek ต่อมาเป็นของ Sun Microsystems และอยู่กับ Oracle ตั้งแต่ Oracle ซื้อกิจการ Sun ในปี 2010' },
  { type: 'text', level: 'medium',
    q: 'เทคโนโลยีช่วยจำลองเครื่องใน CPU ของ AMD เรียกว่า AMD-V ส่วนของ Intel เรียกว่าอะไร',
    answers: ['VT-x', 'Intel VT-x', 'Intel Virtualization Technology', 'Virtualization Technology', 'VT'],
    explain: 'Intel เรียกเทคโนโลยีนี้ว่า VT-x (Intel Virtualization Technology) ต้องเปิดใน BIOS/UEFI ก่อนใช้เครื่องจำลอง' }
];
