'use strict';
// Parallel post-test (form B) for w17, index-aligned with quiz (form A) in ../w17.js
module.exports = [
  { type: 'choice', level: 'easy',
    q: 'ในสำนักงานมีไฟล์สำคัญถูกลบ เจ้าของต้องการรู้ว่าบัญชีใดเข้าระบบในช่วงนั้น การให้พนักงานมีบัญชีแยกรายคนช่วยได้อย่างไร',
    options: [
      'ทำให้ไฟล์ที่ถูกลบกลับคืนมาเองโดยอัตโนมัติ',
      'ทำให้สำนักงานไม่ต้องสำรองข้อมูลอีกต่อไป',
      'Event Log ระบุได้ว่าบัญชีใดเข้าระบบเมื่อไร',
      'ทำให้ทุกคนแก้ไขไฟล์ของคนอื่นได้สะดวกขึ้น'
    ],
    correct: 2,
    explain: 'เมื่อทุกคนมีบัญชีของตัวเอง Event Log จะระบุได้ว่าบัญชีใดเข้าระบบหรือทำอะไรเมื่อไร ซึ่งบัญชีร่วมทำไม่ได้',
    why: ['บัญชีผู้ใช้ไม่ได้กู้ไฟล์ที่ถูกลบ', 'ยังต้องสำรองข้อมูลเสมอ บัญชีรายคนไม่ได้แทนการสำรอง', '', 'บัญชีแยกช่วยแยกสิทธิ์ ไม่ได้ทำให้แก้ไฟล์ของคนอื่นได้ง่ายขึ้น'] },
  { type: 'choice', level: 'easy',
    q: 'เครื่องมือใดของ Windows รวม Local Users and Groups ไว้ในหน้าต่างเดียวกับ Event Viewer, Device Manager และ Disk Management',
    options: ['Task Manager', 'Computer Management', 'Control Panel → Mouse', 'Windows Defender Firewall'],
    correct: 1,
    explain: 'Computer Management รวมเครื่องมือดูแลระบบหลายอย่างไว้ด้วยกัน รวมถึง Local Users and Groups ภายใต้ System Tools เปิดได้จากคลิกขวาปุ่ม Start หรือ This PC → Manage',
    why: ['Task Manager ใช้ดูโปรแกรมและการใช้ทรัพยากร', '', 'หน้า Mouse ใช้ตั้งค่าเมาส์', 'ไฟร์วอลล์ใช้ควบคุมการเชื่อมต่อเครือข่าย'] },
  { type: 'choice', level: 'medium',
    q: 'บัญชี printsvc ใช้เป็นบัญชีบริการที่ผู้ดูแลคุมรหัสผ่านเอง และไม่ต้องการให้ผู้ใช้บัญชีนั้นเปลี่ยนรหัสผ่านเอง ควรติ๊กตัวเลือกใดในหน้า Properties',
    options: ['User cannot change password', 'Account is disabled', 'Account is locked out', 'Member Of → Remove group'],
    correct: 0,
    explain: 'User cannot change password ห้ามผู้ใช้บัญชีนั้นเปลี่ยนรหัสเอง เหมาะกับบัญชีบริการหรือบัญชีที่ผู้ดูแลต้องคุมรหัส',
    why: ['', 'Account is disabled ทำให้บัญชีใช้เข้าระบบไม่ได้เลย บริการจะทำงานไม่ได้', 'Account is locked out แสดงเมื่อบัญชีถูกล็อกจากการใส่รหัสผิด ไม่ใช่ตัวเลือกห้ามเปลี่ยนรหัส', 'การเอาออกจากกลุ่มไม่เกี่ยวกับการเปลี่ยนรหัสผ่าน'] },
  { type: 'choice', level: 'medium',
    q: 'เครื่อง ACC-PC02 ต้องการเพิ่มบัญชีภายในเครื่อง somchai เข้ากลุ่ม Accounting โดยพิมพ์ในหน้าต่าง Select Users แล้วกด Check Names ควรพิมพ์ข้อใด',
    options: ['ACC-PC02/somchai', 'somchai\\ACC-PC02', 'ACC-PC02\\somchai', '\\\\ACC-PC02\\somchai'],
    correct: 2,
    explain: 'บัญชีภายในเครื่องเขียนในรูปแบบ ชื่อเครื่อง\\ชื่อผู้ใช้ เพื่อบอกว่าเป็นบัญชีของเครื่อง ACC-PC02 ถ้าถูกต้องชื่อจะถูกขีดเส้นใต้หลังกด Check Names',
    why: ['Windows ใช้ \\ คั่น ไม่ใช่ /', 'ต้องเขียนชื่อเครื่องไว้หน้าชื่อผู้ใช้', '', 'รูปแบบที่ขึ้นต้นด้วย \\\\ คือ UNC path สำหรับเปิดแชร์'] },
  { type: 'choice', level: 'hard',
    q: 'บนเครื่อง Windows 10 Home ต้องการสร้างกลุ่ม Students แล้วเพิ่ม std01 เข้ากลุ่ม วิธีใดทำได้จริง',
    options: [
      'เปิด lusrmgr.msc แล้วคลิกขวา Groups เลือก New Group',
      'ใช้ net localgroup สร้างกลุ่มและเพิ่ม std01 ใน cmd แบบผู้ดูแล',
      'เปิด wf.msc แล้วสร้าง Inbound Rule ชื่อ Students ให้บัญชี std01',
      'เข้าระบบด้วยบัญชี Guest แล้วสร้างกลุ่มจากหน้า Settings'
    ],
    correct: 1,
    explain: 'รุ่น Home ไม่มี Local Users and Groups แต่คำสั่ง net localgroup ใช้ได้ทุกรุ่น ต้องรันใน Command Prompt แบบ Run as administrator',
    why: ['lusrmgr.msc ใช้ไม่ได้ในรุ่น Home', '', 'wf.msc คือไฟร์วอลล์ ไม่ได้สร้างกลุ่มผู้ใช้', 'Guest ถูกปิดไว้และไม่มีสิทธิ์จัดการบัญชี'] },
  { type: 'choice', level: 'medium',
    q: 'หลังติดตั้ง Windows 11 ใหม่ เปิด lusrmgr.msc แล้วเห็นบัญชี Administrator และ Guest มีไอคอนลูกศรชี้ลง หมายความว่าอย่างไร',
    options: [
      'ทั้งสองบัญชีถูกลบแล้วและรอระบบล้างออก',
      'ทั้งสองบัญชีถูกล็อกเพราะใส่รหัสผิดหลายครั้ง',
      'ทั้งสองบัญชีกำลังล็อกอินใช้งานอยู่ในขณะนี้',
      'ทั้งสองบัญชีถูกปิดใช้งานเป็นค่าเริ่มต้น'
    ],
    correct: 3,
    explain: 'Windows สร้างบัญชี built-in Administrator และ Guest ไว้แต่ปิดใช้งาน (Disabled) เป็นค่าเริ่มต้น ลูกศรชี้ลงคือสัญลักษณ์ของบัญชีที่ถูกปิด',
    why: ['บัญชีที่ถูกลบจะไม่แสดงในรายการ', 'การล็อกจากรหัสผิดไม่ใช่สาเหตุของสถานะเริ่มต้นนี้', 'ลูกศรชี้ลงไม่ได้หมายถึงกำลังล็อกอิน', ''] },
  { type: 'multi', level: 'medium',
    q: 'คำสั่งใดใช้ได้ถูกต้องตามที่อธิบาย (เลือกได้หลายข้อ)',
    options: [
      'net share std05 /add เพื่อสร้างบัญชี std05',
      'net localgroup Students std05 /add เพื่อเพิ่ม std05 เข้ากลุ่ม',
      'ipconfig /all เพื่อดูกลุ่มที่บัญชีสังกัด',
      'net user std05 /delete เพื่อลบบัญชี std05',
      'whoami เพื่อดูชื่อเครื่องและบัญชีที่กำลังใช้'
    ],
    correct: [1, 3, 4],
    explain: 'net localgroup ชื่อกลุ่ม ชื่อผู้ใช้ /add เพิ่มสมาชิก net user ชื่อ /delete ลบบัญชี และ whoami แสดงบัญชีปัจจุบัน ส่วน net share ใช้จัดการแชร์ และ ipconfig แสดงค่าเครือข่าย' },
  { type: 'multi', level: 'hard',
    q: 'สำนักงานมีพนักงาน 8 คนในสองแผนก ข้อใดเป็นแนวทางจัดการบัญชีที่ดี (เลือกได้หลายข้อ)',
    options: [
      'ใช้บัญชีผู้ดูแลที่ตั้งชื่อเอง และใช้บัญชีมาตรฐานในงานประจำวัน',
      'เปิด built-in Administrator ไว้ใช้ทุกวันเพราะไม่ถูก UAC ถาม',
      'สร้างกลุ่มตามแผนกแล้วกำหนดสิทธิ์ให้กลุ่ม',
      'ใช้บัญชี Office เดียวกันทั้งสำนักงานเพื่อจำง่าย'
    ],
    correct: [0, 2],
    explain: 'บัญชีผู้ดูแลที่ตั้งชื่อเองร่วมกับบัญชีมาตรฐานลดความเสียหายจากมัลแวร์ และกลุ่มตามแผนกทำให้กำหนดสิทธิ์ครั้งเดียว ส่วน built-in Administrator ควรปิดไว้ และบัญชีร่วมตรวจสอบตัวบุคคลไม่ได้' },
  { type: 'tf', level: 'easy',
    q: 'บัญชีผู้ใช้ใหม่ที่สร้างด้วยหน้าต่าง New User จะถูกเพิ่มเข้ากลุ่ม Administrators โดยอัตโนมัติ ถูกหรือผิด',
    answer: false,
    explain: 'ผิด บัญชีใหม่จะอยู่ในกลุ่ม Users ซึ่งเป็นสิทธิ์ผู้ใช้มาตรฐาน ถ้าต้องการสิทธิ์ผู้ดูแลต้องเพิ่มเข้ากลุ่ม Administrators เอง' },
  { type: 'text', level: 'easy',
    q: 'คำสั่ง net ... std01 /active:no ใช้ปิดใช้งานบัญชี std01 (เติมคำที่หายไป)',
    answers: ['user', 'net user'],
    explain: 'net user ชื่อผู้ใช้ /active:no ปิดใช้งานบัญชี และ /active:yes เปิดกลับ ส่วน net localgroup ใช้จัดการกลุ่ม' }
];
