'use strict';
// Parallel post-test (form B) for w3, index-aligned with quiz (form A) in ../w3.js
module.exports = [
  { type: 'choice', level: 'easy',
    q: 'มาตรฐาน 802.3 (Ethernet) และ 802.11 (Wi-Fi) ถูกกำหนดโดยองค์กรใด',
    options: ['ISO', 'EIA/TIA', 'IEEE', 'ITU'],
    correct: 2,
    explain: 'IEEE (Institute of Electrical and Electronics Engineers) กำหนดมาตรฐานตระกูล 802 เช่น 802.3 Ethernet และ 802.11 Wi-Fi',
    why: ['ISO พัฒนาแบบจำลอง OSI 7 ชั้น', 'EIA/TIA กำหนดมาตรฐานการเดินสายในอาคาร เช่น TIA-568', '', 'ITU ดูแลมาตรฐานโทรคมนาคมและคลื่นความถี่'] },
  { type: 'choice', level: 'medium',
    q: 'เราเตอร์อ่าน IP Address ปลายทางของข้อมูล แล้วเลือกเส้นทางเพื่อส่งต่อไปยังอีกเครือข่ายหนึ่ง หน้าที่นี้เกิดขึ้นที่ชั้นใดของ OSI เป็นหลัก',
    options: ['Network', 'Data Link', 'Transport', 'Session'],
    correct: 0,
    explain: 'ชั้น Network (ชั้น 3) กำหนดที่อยู่เชิงตรรกะ (IP Address) และหาเส้นทางข้ามเครือข่าย PDU ของชั้นนี้คือ Packet',
    why: ['', 'Data Link ส่งเฟรมภายในเครือข่ายเดียวกันโดยใช้ MAC Address', 'Transport ดูแลการส่งจากต้นทางถึงปลายทางและหมายเลขพอร์ต', 'Session เปิด รักษา และปิดการเชื่อมต่อระหว่างสองฝั่ง'] },
  { type: 'choice', level: 'medium',
    q: 'เมื่อเทียบ TCP/IP Model กับ OSI Model ชั้น Network Access (Link) ของ TCP/IP ตรงกับชั้นใดของ OSI',
    options: ['Network และ Data Link', 'Transport และ Network', 'Data Link และ Physical', 'Physical เพียงชั้นเดียว'],
    correct: 2,
    explain: 'Network Access ของ TCP/IP รวมหน้าที่ของชั้น 2 Data Link และชั้น 1 Physical ของ OSI ตัวอย่างเช่น Ethernet และ Wi-Fi',
    why: ['ชั้น Network ของ OSI ตรงกับชั้น Internet ของ TCP/IP', 'Transport และ Network ตรงกับชั้น Transport และ Internet ตามลำดับ', '', 'Network Access ครอบคลุมทั้ง Data Link และ Physical ไม่ใช่ชั้นเดียว'] },
  { type: 'choice', level: 'easy',
    q: 'บลูทูธซึ่งใช้เชื่อมหูฟังกับมือถือ มีพื้นฐานมาจากมาตรฐาน IEEE กลุ่มใด',
    options: ['IEEE 802.3', 'IEEE 802.15', 'IEEE 802.11', 'IEEE 802.16'],
    correct: 1,
    explain: 'IEEE 802.15 เป็นมาตรฐาน Wireless PAN โดย 802.15.1 เป็นพื้นฐานของบลูทูธ',
    why: ['802.3 คือ Ethernet แบบใช้สาย', '', '802.11 คือ Wireless LAN หรือ Wi-Fi', '802.16 คือ Wireless MAN (WiMAX)'] },
  { type: 'choice', level: 'hard',
    q: 'เครื่องหนึ่งตั้ง IP Address เป็น 192.169.1.5 ข้อใดถูกต้อง',
    options: ['เป็น Class C และเป็น Private IP', 'เป็น Class B และเป็น Private IP', 'เป็น Class C และเป็น Public IP', 'เป็น Class A และเป็น Public IP'],
    correct: 2,
    explain: 'ออกเตตแรก 192 อยู่ในช่วง 192-223 จึงเป็น Class C แต่ช่วง Private ของคลาสนี้คือ 192.168.0.0/16 เท่านั้น 192.169 อยู่นอกช่วง จึงเป็น Public IP',
    why: ['192.169 ไม่อยู่ในช่วง 192.168.0.0/16 จึงไม่ใช่ Private', 'Class B ต้องมีออกเตตแรก 128-191', '', 'Class A ต้องมีออกเตตแรก 1-126'] },
  { type: 'choice', level: 'medium',
    q: 'ห้องกราฟิกเก่ามีเครื่อง Macintosh รุ่นดั้งเดิมที่ใช้ชุดโปรโตคอลของ Apple ซึ่งค้นหาอุปกรณ์ในเครือข่ายได้อัตโนมัติ ชุดโปรโตคอลนั้นคือข้อใด',
    options: ['NetBEUI', 'TCP/IP', 'IPX/SPX', 'AppleTalk'],
    correct: 3,
    explain: 'AppleTalk เป็นชุดโปรโตคอลของ Apple สำหรับ Macintosh รุ่นเก่า มีจุดเด่นที่ค้นหาอุปกรณ์อัตโนมัติ ภายหลังถูกแทนที่ด้วย TCP/IP',
    why: ['NetBEUI ใช้ใน Windows ขนาดเล็กยุคเก่า', 'TCP/IP เป็นมาตรฐานกลางของทุกระบบในปัจจุบัน ไม่ใช่ชุดโปรโตคอลเฉพาะของ Apple', 'IPX/SPX เป็นของ Novell NetWare', ''] },
  { type: 'multi', level: 'medium',
    q: 'ข้อใดเป็น Private IP Address (เลือกได้หลายข้อ)',
    options: ['172.31.200.1', '172.15.0.1', '192.168.0.1', '11.0.0.1'],
    correct: [0, 2],
    explain: 'Private IP มีช่วง 10.0.0.0/8, 172.16.0.0/12 (172.16-172.31) และ 192.168.0.0/16 ดังนั้น 172.31.200.1 และ 192.168.0.1 เป็น Private ส่วน 172.15 อยู่ต่ำกว่า 172.16 และ 11.0.0.1 อยู่นอกช่วง 10.x จึงเป็น Public' },
  { type: 'multi', level: 'hard',
    q: 'ข้อใดระบุหน่วยข้อมูล (PDU) ประจำชั้นของ OSI ได้ถูกต้อง (เลือกได้หลายข้อ)',
    options: ['Network - Frame', 'Transport - Segment', 'Physical - Packet', 'Data Link - Frame'],
    correct: [1, 3],
    explain: 'Transport = Segment (TCP) หรือ Datagram (UDP), Network = Packet, Data Link = Frame และ Physical = Bit' },
  { type: 'tf', level: 'easy',
    q: 'แม้ไม่มีมาตรฐานหรือโปรโตคอลกลาง อุปกรณ์เครือข่ายต่างยี่ห้อก็ยังสื่อสารกันได้เสมอ ข้อความนี้ถูกหรือผิด',
    answer: false,
    explain: 'ผิด อุปกรณ์ต่างยี่ห้อทำงานร่วมกันได้เพราะผู้ผลิตทำตามมาตรฐานและโปรโตคอลเดียวกัน เช่น IEEE 802.3 และ TCP/IP ถ้าไม่มีข้อตกลงกลางก็อาจสื่อสารกันไม่ได้' },
  { type: 'text', level: 'easy',
    q: 'Subnet Mask เริ่มต้น (Default) ของ IP Address คลาส B คืออะไร',
    answers: ['255.255.0.0', '/16', '16'],
    explain: 'Class B ใช้ 2 ไบต์แรกเป็นส่วนเครือข่าย จึงมี Subnet Mask 255.255.0.0 หรือ /16 และมีโฮสต์ใช้งานได้ 2^16 - 2 = 65,534 เครื่องต่อวง' }
];
